config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("doctors.urls")),
    path('', include("invoice.urls")),
    path('', include("patients.urls")),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

invoice/urls.py
from django.contrib import admin
from django.urls import path
from .views import DeleteInvoiceView, InvoiceListView, createInvoice, invoice_search, view_PDF

app_name = 'invoice'
urlpatterns = [
    path('invoice/', InvoiceListView.as_view(), name="invoice-list"),
    path('create/', createInvoice, name="invoice-create"),
    path('invoice-detail/<id>', view_PDF, name='invoice-detail'),
    path('invoice/s', invoice_search, name='invoice_search'),
    path('delete/invoice/<int:pk>/', DeleteInvoiceView.as_view(), name='invoice-delete'),
    # path('invoice-download/<id>', generate_PDF, name='invoice-download')
]

invoice/models.py
from django.db import models
from accounts.models import CustomUser
from patients.models import Patient
from django.utils import timezone
from django.utils.timezone import now

class Invoice(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE, verbose_name="bemor")
    # default=timezone.now bo'lsa unda user dateni kiritishiga to'g'ri kelyapti,
    # auto_now = True bo'lsa, user kiritmasdan saqlayapti lekin, o'zgartirib bo'lmayapti.
    date = models.DateTimeField(blank=True, auto_now = True)
    # due_date = models.DateField(null=True, blank=True)
    total_amount = models.DecimalField(max_digits=9, decimal_places=2, blank=True, null=True)
    status = models.BooleanField(default=False)
    doctor = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    def __str__(self):
        return str(self.patient)
    
    def get_status(self):
        return self.status

    # def save(self, *args, **kwargs):
        # if not self.id:             
        #     self.due_date = datetime.datetime.now()+ datetime.timedelta(days=15)
        # return super(Invoice, self).save(*args, **kwargs)

class LineItem(models.Model):
    patient = models.ForeignKey(Invoice, on_delete=models.CASCADE)
    service = models.TextField()
    quantity = models.IntegerField()
    rate = models.DecimalField(max_digits=9, decimal_places=2)
    amount = models.DecimalField(max_digits=9, decimal_places=2)
    

    def __str__(self):
        return str(self.patient)
    

invoice/forms.py
from django import forms
from django.forms import formset_factory
from .models import Invoice, LineItem

class InvoiceForm(forms.ModelForm):
    class Meta:
        model = Invoice
        
        
        fields = ['patient']
# class InvoiceForm(forms.Form):
    
#         # fields = ['customer', 'message']
#     customer = forms.CharField(
#         label='Customer',
#         widget=forms.TextInput(attrs={
#             'class': 'form-control',
#             'placeholder': 'Customer/Company Name',
#             'rows':1
#         })
#     )
    # customer_email = forms.CharField(
    #     label='Customer Email',
    #     widget=forms.TextInput(attrs={
    #         'class': 'form-control',
    #         'placeholder': 'customer@company.com',
    #         'rows':1
    #     })
    # )
    # billing_address = forms.CharField(
    #     label='Billing Address',
    #     widget=forms.TextInput(attrs={
    #         'class': 'form-control',
    #         'placeholder': '',
    #         'rows':1
    #     })
    # )
    # message = forms.CharField(
    #     label='Message/Note',
    #     widget=forms.TextInput(attrs={
    #         'class': 'form-control',
    #         'placeholder': 'message',
    #         'rows':1
    #     })
    # )
    
class LineItemForm(forms.Form):
    
    service = forms.CharField(
        required=True,
        label='Service/Product',
        widget=forms.TextInput(attrs={
            'required':True,
            'class': 'form-control input',
            'placeholder': 'XIZMAT TURI'
        })
    )
   
    quantity = forms.IntegerField(
        required=True,
        label='Qty',
        widget=forms.TextInput(attrs={
            'required':True,
            'class': 'form-control input quantity',
            'placeholder': 'SONI'
        }) #quantity should not be less than one
    )
    rate = forms.DecimalField(
        required=True,
        label='Rate $',
        widget=forms.TextInput(attrs={
            'required':True,
            'class': 'form-control input rate required',
            'placeholder': 'NARXI'
        })
    )
    
  
        # return any errors if found
        
    
    # amount = forms.DecimalField(
    #     disabled = True,
    #     label='Amount $',
    #     widget=forms.TextInput(attrs={
    #         'class': 'form-control input',
    #     })
    # )
    
LineItemFormset = formset_factory(LineItemForm, extra=1)

invoice/views.py
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.template.loader import get_template
from django.http import HttpResponse
from django.views import View

from patients.models import Patient
from .models import LineItem, Invoice
from .forms import LineItemFormset, InvoiceForm
from django.core.paginator import Paginator
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from django.views.generic.edit import DeleteView
from django.urls import reverse_lazy


def invoice_search(request):
    search = request.GET.get("search")
    invoices = Invoice.objects.filter(doctor=request.user).order_by('date')
    paginator = Paginator(invoices, 20)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    
    if search:
        page_obj = invoices.filter(patient__name__icontains=search).order_by('date')
        print(invoices)

    context = {"search": search, 'page_obj': page_obj}
    return render(request, 'invoice/invoice-list1.html', context)

class InvoiceListView(LoginRequiredMixin, View):
    def get(self, request):
        
        
        invoices = Invoice.objects.filter(doctor=request.user).order_by('date')
        
        paginator = Paginator(invoices, 20)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)

        context = {
            "invoices":invoices,
            'page_obj': page_obj,
            # 'lineitem':lineitem
        }
        
        return render(self.request, 'invoice/invoice-list.html', context)
    
    def post(self, request):        
        # import pdb;pdb.set_trace()
        invoice_ids = request.POST.getlist("invoice_id")
        invoice_ids = list(map(int, invoice_ids))

        update_status_for_invoices = int(request.POST['status'])
        invoices = Invoice.objects.filter(id__in=invoice_ids)
        # import pdb;pdb.set_trace()
        if update_status_for_invoices == 0:
            invoices.update(status=False)
        else:
            invoices.update(status=True)

        return redirect('invoice:invoice-list')


def createInvoice(request):
    """
    Invoice Generator page it will have Functionality to create new invoices, 
    this will be protected view, only admin has the authority to read and make
    changes here.
    """
    if request.user.is_authenticated:
        patients=Patient.objects.filter(doctor=request.user)
    
        
        if request.method == 'GET':
            formset = LineItemFormset(request.GET or None)
            form = InvoiceForm(request.GET or None)
        elif request.method == 'POST':
            
            
            # if request.POST.get('service') == None:
            #     return render(request, "invoice/invoice-create.html",{'error':True})
            form = InvoiceForm(request.POST)
            formset = LineItemFormset(request.POST)
            # customer = Patient.objects.get_or_create()
            
            if form.is_valid():
                invoice = Invoice.objects.create(patient=form.cleaned_data.get("patient"),doctor=request.user,
                        date=form.data["date"],
                        # due_date=form.data["due_date"], 
                        # message=form.data["message"],
                        )
                # invoice.save()
                
            if formset.is_valid():
                
                # import pdb;pdb.set_trace()
                # extract name and other data from each form and save
                total = 0
                for form in formset:
                    
                    service = form.cleaned_data.get('service')
                    quantity = form.cleaned_data.get('quantity')
                    rate = form.cleaned_data.get('rate')
                    
                    if service and quantity and rate:
                        amount = float(rate)*float(quantity)
                        total += amount
                        LineItem(patient=invoice,
                                service=service,
                                quantity=quantity,
                                rate=rate,
                                amount=amount,
                                ).save()
                invoice.total_amount = total
                # print(request.POST.get('service'))
                # print(request.POST.get('quantity'))
                # print(request.POST.get('rate'))
                invoice.save()
                # try:
                #     generate_PDF(request, id=invoice.id)
                # except Exception as e:
                #     print(f"********{e}********")
                
                
                return redirect('invoice:invoice-list')
            
        context = {
            "patients":patients,
            "title" : "Invoice Generator",
            "formset": formset,
            "form": form,
            
        }
        return render(request, 'invoice/invoice-create.html', context)


def view_PDF(request, id=None):
    invoice = get_object_or_404(Invoice, id=id)
    lineitem = invoice.lineitem_set.all()

    context = {
        "company": {
            "name": "Rohat Dent",
            "address" :"Istiqlol ko'chasi, 34",
            "phone": "(998) 99 2292240",
            "email": "xmirzo001@gmail.com",
        },
        "invoice_id": invoice.id,
        "invoice_total": invoice.total_amount,
        "patient": invoice.patient,
        "date": invoice.date,
        "lineitem": lineitem,

    }
    return render(request, 'invoice/pdf_template.html', context)

# def generate_PDF(request, id):
#     # Use False instead of output path to save pdf to a variable
#     pdf = pdfkit.from_url(request.build_absolute_uri(reverse('invoice:invoice-detail', args=[id])), False)
#     response = HttpResponse(pdf,content_type='application/pdf')
#     response['Content-Disposition'] = 'attachment; filename="invoice.pdf"'

#     return response


# def change_status(request):
#     return redirect('invoice:invoice-list')

# def view_404(request,  *args, **kwargs):

#     return redirect('invoice:invoice-list')

class DeleteInvoiceView(UserPassesTestMixin, LoginRequiredMixin, DeleteView):
    model = Invoice
    template_name = 'invoice/invoice_delete.html'
    success_url = reverse_lazy('invoice:invoice-list')

    def test_func(self): 
        return self.request.user
        

invoice/templates/invoice/base.html
<!doctype html>{% load static %}
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <link rel="shortcut icon" href="/media/logo.png">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
   
     <link href="{% static 'css/bulma-calendar.min.css' %}" rel="stylesheet">
     <link href="{% static 'js/bulma-calendar.min.js' %}" rel="stylesheet">
     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.0/css/bulma.min.css">
     <link href="{% static 'iconfont/material-icons.css' %}" rel="stylesheet" />

     {% block custom_css %}{% endblock %}
   
     {% block title %}
     <title>TO'LOVLAR</title>
     {% endblock title %}

</head>
<body>
     
    <div class="container">
                {% block content %}
                {% endblock %}
            </div>
    <footer class="footer">
        <center><p class="has-text-weight-bold">Mirzo Uzakov</p>
        </center>
        </footer>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
     {% block custom_js %}{% endblock %}
</body>

invoice/templates/invoice/invoice-create.html
{% extends "invoice/base.html" %}



{% block content %}
<style>
    select {
        padding: 70px;
        
        border-radius: 2px;
      }
</style>
<br>
<p class="title is-3 has-text-centered"><span class="material-icons-sharp">paid</span> Yangi to'lov qo'shish </p>

<section class="hero is-fullheight">
 
    <div class="container">
        
        <div class="card white-ter">
            
            <div class="hero-body">
                
                <form class="" method="POST" action="{% url 'invoice:invoice-create' %}">
                    <p class="title is-6 is-spaced has-text-centered"><span class="material-icons-sharp">
                        people_alt
                        </span> Bemor:</p>
                    {% csrf_token %}
                   
                    <div class="columns is-centered" >
                        
                           
                         
                            <div class="field is-medium">
                                
                                <select id="patient" name="patient" >
                                   
                                    <option selected disabled="true">---------</option>
                                    {% for pat in patients %}
        
                                    <option value="{{pat.id}}">{{ pat.name }}</option>
                                    {% endfor %}
                                </select>
                              </div>

                       
                    </div>  
                        <input type="hidden" name="doctor" value="{{ request.user.id }}">

                        
                 
                    <div class="columns is-centered">
                       
                        <div class="column is-one-third">
                            
                          <input class="input" type="hidden" name="date">
                            
                        </div>
                       <br>
                    </div>


                    <table class="table is-fullwidth is-bordered is-hoverable is-striped">
                        <tbody>
                            <thead>
                                <tr>
                                    <th>XIZMAT</th>
                                    <th>SONI</th>
                                    <th>NARXI</th>
                                    <th>SUMMA</th>
                                    <th>BOSHQA</th>
                                </tr>
                                {{ formset.management_form }}
                                {% for form in formset %}
                                <tr>
                                    <td>{{form.service}}</td>
                                    <td>{{form.quantity}}</td>
                                    <td>{{form.rate}}</td>
                                    <td class="amount"></td>
                                    <td>
                                        <div class="input-group-append">
                                            <button
                                                class="button is-small btn btn-success add-form-row">+</button>&nbsp;
                                            <!-- <button class="button is-small btn btn-warning remove-form-row">-</button> -->
                                        </div>
                                    </td>
                                </tr>
                                {% endfor %}
                            </thead>
                        </tbody>

                    </table>
                    <div class="row spacer">
                        <div class="buttons is-centered">
                            
                            <button type="submit" class="buttons is-centered button btn btn-block is-info is-half "><span class="material-icons-sharp">add_box</span>Qo'shish </button>
                        </div>
                    </div>
                    <br>
                    <div class="columns">
                        <div class="column">
                            <h3 class="title is-4">Umumiy(so'm): <span id="total"></span></h3>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="buttons is-centered" style="margin-top: 15px;">
            
            <a href="{% url 'invoice:invoice-list' %}">
            <button class="button is-danger"><span class="material-icons-sharp">
                arrow_back_ios
                </span>Ortga Qaytish</button>
          </div>
            </a>
    </div>
    
</section>


{% endblock %}

{% block custom_js %}


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js" integrity="sha512-2ImtlRlf2VVmiGZsjm9bEyhjGW4dU7B6TNwh/hx/iSByxNENtj3WVE6o/9Lj4TJeVXPi4bnOIMXFIJJAeufa0A==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" integrity="sha512-nMNlpuaDPrqlEls3IX/Q56H36qvBASwb3ipuo3MxeWbsQB1881ox0cRv7UPTgBlriqoynt35KjEwgGUeUXIPnw==" crossorigin="anonymous" referrerpolicy="no-referrer" />


<script>
    $(document).ready(function()
    {
      $('#patient').select2({
        minimumInputLength: 1,
        theme: "classic",
        language: { inputTooShort: function () { return 'Bemor ismining 1-harfini kiriting'; } },

        
      });
    });
  </script>
<script type="text/javascript">
    $('table input').on("input", function () {
        var total = []
        var $tr = $(this).closest('tr');
        var textValue1 = $("input.rate", $tr).val();
        var textValue2 = $('input.quantity', $tr).val();
        amt = textValue1 * textValue2;
        // console.log(amt);
        $('.amount', $tr).html(amt);
        calc_total();
    });

    function calc_total() {
        var sum = 0;
        $(".amount").each(function () {
            sum += parseFloat($(this).text());
        });
        console.log(sum);
        $('#total').text(sum);
    }
</script>


<script type="text/javascript">
    function updateElementIndex(el, prefix, ndx) {
        var id_regex = new RegExp('(' + prefix + '-\\d+)');
        var replacement = prefix + '-' + ndx;
        if ($(el).attr("for")) $(el).attr("for", $(el).attr("for").replace(id_regex, replacement));
        if (el.id) el.id = el.id.replace(id_regex, replacement);
        if (el.name) el.name = el.name.replace(id_regex, replacement);
    }
    function cloneMore(selector, prefix) {
        var newElement = $(selector).clone(true);
        console.log(newElement);
        var total = $('#id_' + prefix + '-TOTAL_FORMS').val();
        newElement.find(':input:not([type=button]):not([type=submit]):not([type=reset])').each(function () {
            var name = $(this).attr('name')
            if (name) {
                name = name.replace('-' + (total - 1) + '-', '-' + total + '-');
                var id = 'id_' + name;
                $(this).attr({ 'name': name, 'id': id }).val('').removeAttr('checked');
            }
        });
        newElement.find('label').each(function () {
            var forValue = $(this).attr('for');
            if (forValue) {
                forValue = forValue.replace('-' + (total - 1) + '-', '-' + total + '-');
                $(this).attr({ 'for': forValue });
            }
        });
        total++;
        $('#id_' + prefix + '-TOTAL_FORMS').val(total);
        $(selector).after(newElement);
        // $("div.form-row.button.is-primary").not(":last").hide();
        // var conditionRow = $('.form-row:not(:last)');
        // conditionRow.find('.button.is-primary')
        // .hide();
        // .removeClass('btn-success').addClass('btn-danger')
        // .removeClass('add-form-row').addClass('remove-form-row')
        // .html('-');
        return false;
    }
    function deleteForm(prefix, btn) {
        var total = parseInt($('#id_' + prefix + '-TOTAL_FORMS').val());
        if (total > 1) {
            btn.closest('.form-row').remove();
            var forms = $('.form-row');
            $('#id_' + prefix + '-TOTAL_FORMS').val(forms.length);
            for (var i = 0, formCount = forms.length; i < formCount; i++) {
                $(forms.get(i)).find(':input').each(function () {
                    updateElementIndex(this, prefix, i);
                });
            }
        }
        return false;
    }
    $(document).on('click', '.add-form-row', function (e) {
        e.preventDefault();
        cloneMore('table tr:last', 'form');
        return false;
    });
    $(document).on('click', '.remove-form-row', function (e) {
        e.preventDefault();
        deleteForm('form', $(this));
        return false;
    });

</script>
{% endblock %}

invoice/templates/invoice/invoice-list.html
{% extends 'invoice/base.html' %}
    {% block title %}
     <title>TO'LOVLAR</title>
    {% endblock title %}
{% load static %}
{% block content %}


<div class="columns is-centered has-text-centered">
    <div class="column is-half">
        <div class="card has-background-white-ter">
            <h1 class="title is-3"></h1>
        </div>
    </div>

</div>
<div class="card">
    <header class="card-header">
        <p class="card-header-title">
            <a href="{% url 'dashboard' %}"><span class="material-icons-sharp">grid_view</span></a> Dashboard / <a
                href="{% url 'patients' %}"><span class="material-icons-sharp">people_alt</span> </a> Bemorlar
        </p>
        <p class="card-header-title">
            Hamma to'lovlar / To'lov statusini o'zgartirish &nbsp;
            <button class="button is-link">
                <a href="{% url 'invoice:invoice-create' %}" class="has-text-white">Yangi to'lov</a>
            </button>
        </p>
    </header>

    <span class="card-header-title  is-centered ">
        <p class="control">
        <form hx-get="{% url 'invoice:invoice_search' %}" hx-target="#content" hx-trigger="submit, input delay:0.3s">
            <input class="input is-link" name="search" type="text" placeholder="🔎Qidirish">
        </form>
        </p>
    </span>

    <form action="{% url 'invoice:invoice-list' %}" method="post">{% csrf_token %}



        <div class="card-content table-container">
            <div class="content" id="content">
                {% include 'invoice/invoice-list1.html' %}
            </div>
        </div>

</div><br /><br /><br />
<div class="card has-background-white-ter">
    <header class="card-header">
        <p class="card-header-title">
            To'lov statusini o'zgartirish
        </p>
    </header>
    <div class="card-content">
        <div class="select">
            <select id="status" name="status">
                <option value="1">✔️To'langan</option>
                <option value="0">❌To'lanmagan</option>
            </select>
        </div>
        <input class="button is-info" type="submit" class="btn" value="O'zgartirish" name="mybtn">
    </div>
</div>
</form>

<script type="text/javascript" src="{% static 'js/htmx.min.js' %}"></script>
<script>
    document.body.addEventListener('htmx:configRequest', (event) => {
        event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
    })
</script>
{% endblock content %}

invoice/templates/invoice/invoice-list1.html
<table class="table is-fullwidth is-bordered is-hoverable is-striped">
    <tbody>
        <thead>
            <tr>
                <th></th>
                <th>RAQAMI</th>
                <th>BEMOR</th>
                <th>SANA</th>
                
                
                <th>SUMMA</th>
                <th>STATUS</th>
                <th>SHIFOKOR</th>
                <th>KO'RISH</th>
                

            </tr>
        </thead>
        {% for invoice in page_obj %}
        <tr>
            
            <td><input class="checkbox" type="checkbox" value="{{invoice.id}}"  name="invoice_id" size="2" />
            </td>
            <td width="1%">#{{invoice.id}}</td>
            <td width="9%">{{invoice.patient}}</td>
            <td> {{invoice.date}}</td>
           
           
            <td>{{invoice.total_amount}}</td>
            <td>
                {% if invoice.get_status %}
                <a class="button is-small is-success" href="#">To'langan</a>
                {% else %}
                <a class="button is-small is-warning" href="#">To'lanmagan</a>
                {% endif %}
                
            </td>
            <td>{{invoice.doctor}}</td>
            <td width="10%"><a href="{% url 'invoice:invoice-detail' id=invoice.id %}">
                <div class="button is-small is-info"><span class="material-icons-outlined">
                    visibility
                    </span></div>
                
            </a>
            <a href="{% url 'invoice:invoice-delete' invoice.id %}">
                <div class="button is-small is-danger"><span class="material-icons-outlined">
                    delete
                    </span></div>
                
            </a>
        </td>
            
          
        </tr>
        {% endfor %}

    </tbody>
</table>
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
        <button class="button is-rounded"> <a href="?page=1">&laquo; boshi</button></a>
            <button class="button is-rounded"> <a href="?page={{ page_obj.previous_page_number }}">⏮️oldingi</button></a>
        {% endif %}

        <span class="current tag is-light is-medium">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
        <button class="button is-rounded"> <a href="?page={{ page_obj.next_page_number }}">keyingi⏭️</button></a>
           

        <button class="button is-rounded">   <a href="?page={{ page_obj.paginator.num_pages }}">oxirgi &raquo;</button> </a>
        {% endif %}
    </span>
</div>

invoice/templates/invoice/invoice_delete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<h1 class="display-6 text-center"> <i class="fa-solid fa-calendar-xmark"></i> Qabulni o'chirish</h1>

<div class="d-flex justify-content-center">
    <div class="col-auto">

        <form action="" method="post">{% csrf_token %}
            <br>
            <p class="fs-4">"{{invoice.patient}}" ismli bemorning <strong>{{invoice.date}}</strong> vaqtidagi <strong>{{invoice.total_amount}}</strong> so'mlik chekni o'chirishni istaysizmi?</p>
            <button class="btn btn-danger ml-2 mx-auto d-block" type="submit">Ha</button>

            <div class="d-flex justify-content-center mt-2"><a href="{% url 'invoice:invoice-list' %}" class="btn btn-secondary" role="button">Yo'q</a></div>
        </form>

    </div>
</div>
{% endblock content %}

invoice/templates/invoice/pdf_template.html
<!DOCTYPE html>{% load static %}

<html lang="en">
  <head>
    <meta charset="utf-8">
    <title> TO'LOV</title>
    <link rel="shortcut icon" href="/media/logo.png">

    <link rel="stylesheet" href="{%static 'css/invoice-template.css' %}" media="all" />
  </head>
  <body>
    <header class="clearfix">
      <div id="logo">
        <img src="/media/pngwing.com.png" style="width: 134px; height:116px"> 
      </div>
      <div id="company">
        <h1 class="name">{{company.name}}</h1>
        <div>{{company.address}}</div>
        <div>{{company.phone}}</div>
        <div><a href="mailto:{{company.email}}">{{company.email}}</a></div>
      </div>
      </div>
    </header>
    <main>
      <div id="details" class="clearfix">
        <div id="client">
          <div class="to">TO'LOV:</div>
          <h2 class="name">{{patient}}</h2>
          <div class="address">{{billing_address}}</div>
          <div class="email"><a href="mailto:{{customer_email}}">{{customer_email}}</a></div>
        </div>
        <div id="invoice">
          <h1>#{{invoice_id}}</h1>
          <div class="date"><strong>To'lov yaratilgan sana:</strong>  {{date}}</div>
          
        </div>
      </div>
      <table border="0" cellspacing="0" cellpadding="0">
        <thead>
          <tr>
            <th class="no">#</th>
            <th class="desc">XIZMAT</th>
            <th class="unit">NARX</th>
            <th class="qty">MIQDOR</th>
            <th class="total">UMUMIY</th>
          </tr>
        </thead>
        <tbody>
			{% for item in lineitem %}
          <tr>
            <td class="no">{{forloop.counter}}</td>
            <td class="desc">{{item.service}}</td>
            <td class="unit">{{item.rate}}</td>
            <td class="qty">{{item.quantity}}</td>
            <td class="total">{{item.amount}}</td>
		  </tr>
		  {% endfor %}
        </tbody>
        <tfoot>
          <tr>
            <td colspan="2"></td>
            <td colspan="2">QO'SHIMCHA TO'LOV</td>
            <td>0 so'm</td>
          </tr>
          <tr>
            <td colspan="2"></td>
            <td colspan="2">SOLIQ 0%</td>
            <td>0 so'm</td>
          </tr>
          <tr>
            <td colspan="2"></td>
            <td colspan="2">UMUMIY TO'LOV MIQDORI</td>
            <td>{{invoice_total}}SO'M</td>
          </tr>
        </tfoot>
      </table>
      <div id="thanks">Raxmat !</div>
      <div id="notices">
        <div>ESLATMA:</div>
        <div class="notice">Siz to'lovni naqd pul yoki plastik karta ko'rinishida amalga oshirishingiz mumkin.</div>
      </div>
    </main>
    <footer>
      Invoice was created on a computer and is valid without the signature and seal.
    </footer>
  </body>
</html>

invoice/templates/invoice/s.html
{% for customer in page_obj %}
    {# Each "contact" is a Contact model object. #}
    {{ customer }}<br>
    ...
{% endfor %}

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>