config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("doctors.urls")),
    path('', include("invoice.urls")),
    path('', include("patients.urls")),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

invoice/urls.py
from django.contrib import admin
from django.urls import path
from .views import DeleteInvoiceView, InvoiceListView, createInvoice, invoice_search, view_PDF

app_name = 'invoice'
urlpatterns = [
    path('invoice/', InvoiceListView.as_view(), name="invoice-list"),
    path('create/', createInvoice, name="invoice-create"),
    path('invoice-detail/<id>', view_PDF, name='invoice-detail'),
    path('invoice/s', invoice_search, name='invoice_search'),
    path('delete/invoice/<int:pk>/', DeleteInvoiceView.as_view(), name='invoice-delete'),
    # path('invoice-download/<id>', generate_PDF, name='invoice-download')
]

templates/dashboard/base_dashboard.html
{% load static %}
{% url 'dashboard' as dashboard_url %}
{% url 'dashboard_week' as dashboard_week_url %}
{% url 'dashboard_next_week' as dashboard_nw_url %}
{% url 'dashboard_prev_week' as dashboard_pw_url %}

{% url 'patients' as patients_url %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <!-- Default CSS -->
  <link rel="stylesheet" href="{% static 'css/style.css' %}" />

  <!-- ASIDE CSS -->
  <link rel="stylesheet" href="{% static 'css/aside.css' %}" />

  <!-- MAIN CSS -->
  <link rel="stylesheet" href="{% static 'css/main1.css' %}" />

  <!-- RIGHT SIDE CSS -->
  <link rel="stylesheet" href="{% static 'css/right-side.css' %}" />

  <!-- MEDIA CSS -->
  <link rel="stylesheet" href="{% static 'css/media.css' %}" />

  <!-- ICONS -->
  <link href="{% static 'iconfont/material-icons.css' %}" rel="stylesheet" />

  <link href="{% static 'fontawesome/fontawesome/css/all.css' %}" rel="stylesheet">

  <link rel="stylesheet" href="//code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">
  


  <title>{% block title %}ROHAT DENT {% endblock title %}</title>
  <link rel="shortcut icon" href="/media/logo.png">
  
</head>

<body>
  <div class="container">
    <aside>
      <a href="{% url 'home' %}">
        <div class="top">
          <div class="logo">
            <img src="/media/logo.png" alt="logo" />
            <h2>ROHAT <span class="danger">DENT</span></h2>
            
          </div>
          <div class="close" id="close-btn">
            <span class="material-icons-sharp">close</span>
          </div>
        </div>
      </a>
      <div class="sidebar">
        <a href="{{ dashboard_url }}" 
        class="{%if request.path == dashboard_url%}active
                {%elif request.path == dashboard_week_url %}active
                {%elif request.path == dashboard_nw_url %}active
                {%elif request.path == dashboard_pw_url %}active
                {% endif %}">
          <span class="material-icons-sharp">dashboard_customize</span>
          <h3>Qabul</h3>
          <span class="message-count">24</span>
        </a>
        <a href="{{ patients_url }}" class="{% if request.path == patients_url %}active{% endif %}">
          <span class="material-icons-sharp">person_outline</span>
          <h3>Bemorlar</h3>
        </a>
        <a href="{% url 'appointment_new' %}">
          <span class="material-icons-sharp">add</span>
          <h3>Qabul Qo'shish</shish>
            
          </h3>
        </a>
        <a href="{% url 'patients_new' %}">
          <span class="material-icons-sharp">person_add</span>
          <h3>Bemor Qo'shish
          </h3>
        </a>
        <a href="{% url 'invoice:invoice-list' %}">
          <span class="material-icons-sharp">payments</span>
          <h3>To'lovlar</h3>
        </a>
        <a href="{% url 'invoice:invoice-create' %}">
          <span class="material-icons-sharp">edit_note</span>
          <h3>To'lov Qo'shish</h3>
        </a>
        <a href="{% url 'app-full-list' %}">
          <span class="material-icons-sharp">format_list_numbered</span>
          <h3>Qabul ro'yxati</h3>
        </a>

        
        <a href="">
          <i class="fa-solid fa-tooth"></i>
          <h3>ROHAT DENT</h3>
        </a>

      </div>
    </aside>

    <!-- ---------------- END OF ASIDE ------------------------ -->


    {% block content %}
    {% endblock content %}
    <div class="right">
      <div class="top">
        <button class="" id="menu-btn">
          <span class="material-icons-sharp">menu</span>
        </button>
        {% comment %}
        <div class="theme-toggler">
          <span class="material-icons-sharp active">light_mode</span>
          <span class="material-icons-sharp">dark_mode</span>
        </div>
        {% endcomment %}
        
    
        <div class="profile">
          <div class="info">
            <p><b>{{user.first_name}} {{user.last_name}}</b></p>
            <small class="text-muted">Doktor</small>
          </div>
    
          <div class="profile-photo">
            <a href="{% url 'doctor_profile' %}"><img src="{{ user.profile_picture.url }}" alt="profile" /></a>
          </div>
        </div>
      </div>
      
  </div>
  
  <script src="{% static 'js/script.js' %}"></script>
  <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
  
  <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>

    <script>
      $( function() {

      $( "#tags" ).autocomplete({
        source: "{% url 'autosuggest' %}",
      });
      });

    </script>
</body>

</html>

templates/dashboard/dashboard.html
{% extends 'dashboard/base_dashboard.html' %}

{% load static %}


{% block content %}

<main>
  <h1>Dashboard</h1>
  {% comment %}
  <div class="data">
    <input type="date" />
  </div>
  {% endcomment %}

  <!-- END OF INSIGHTS -->

  <div class="middle">
    <div class="recent-orders">
      
            
          
          {% comment %}
                 <div class="wrapper">
            <form method="get">
            <div class="search_box">
              <button class="search_btn"><i class="material-icons-sharp">person_search</i></button>
              <input type="text" id="tags" name="q" class="input_search" placeholder="Bemorlar">
              
                </form>
                </div>
              </div>
          {% endcomment %}
            
     

          <div class="wrapper">
            <div class="search_box">
              <form 
              hx-get="{% url 'dashboard_search' %}" 
              hx-target="#dada" 
              hx-trigger="submit, input delay:0.3s">
        
              <input type="text" name="search" class="input_search" placeholder="Qidirish..." value="{{ search }}">
              </form>


            </div>
            <span class="material-icons-sharp" style="padding-left: 6px;">person_search</span>

          </div>

             


          <div class="date button-group"> 
            <button class="button" type="button"><a href="{% url 'dashboard' %}">Kun</button></a> 
           <button class="button" type="button"> <a href="{% url 'dashboard_week' %}">Hafta</button></a> 
             </div>
   
      <div id="dada">
      {% include "dashboard/dashboard_search.html" %}
      </div>
     
    
    {% comment %}
      <a href="#">Hammasini ko'rsatish</a>
      <br>
      {% endcomment %}
        
     
    </div>
  </div>
</main>
<script type="text/javascript" src="{% static 'js/htmx.min.js' %}"></script>
<script>
  document.body.addEventListener('htmx:configRequest', (event) => {
    event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
  })
</script>

  {% endblock content %}


  </body>

  </html>

templates/dashboard/dashboard_next_search.html
<table>
    <thead>
      <tr>
            <th></th>
          {% for k,v in dictweek.items %}
            <th>{{v|date:"D, d/m"}}</th>
          {% endfor %}
      </tr>

    </thead>
    <tbody>
      {% for t in time %}
      <tr>
        <td>{{ t.time|date:"H:i" }}</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
      {% for k,v in dictweek.items %}
        {% for app in appointment %}
          {% if app.time|date:"H" == t.time|date:"H" %}
            {% if app.date == v %}
                <tr>
                  <th></th>
                  
                 
                  {% if k == 'dushanba' %} <td> <a href="{% url 'appointment_detail' app.pk  %}">{{ app.patient }}</a> </td> {% else %} <td></td> {% endif %}
                  {% if k == 'seshanba' %} <td> <a href="{% url 'appointment_detail' app.pk  %}">{{ app.patient }}</a> </td> {% else %} <td></td> {% endif %}
                  
                  {% if k == 'chorshanba' %} <td> <a href="{% url 'appointment_detail' app.pk  %}">{{ app.patient }}</a> </td> {% else %} <td></td> {% endif %}
                 
                  {% if k == 'payshanba' %} <td> <a href="{% url 'appointment_detail' app.pk  %}">{{ app.patient }}</a>  </td> {% else %} <td></td> {% endif %}
                 
                  {% if k == 'juma' %} <td> <a href="{% url 'appointment_detail' app.pk  %}">{{ app.patient }}</a>  </td> {% else %} <td></td> {% endif %}
                 
                  {% if k == 'shanba' %} <td> <a href="{% url 'appointment_detail' app.pk  %}">{{ app.patient }}</a> </td> {% else %} <td></td> {% endif %}
                 
                  {% if k == 'yakshanba' %} <td><a href="{% url 'appointment_detail' app.pk  %}">{{ app.patient }}</a>  </td> {% else %} <td></td> {% endif %}
                 
                  <td></td>
                  <td></td>
                  <td></td>
                  <td></td>
                  <td></td>
                  <td></td>


          {% endif %}
            {% endif %}
                {%endfor%}
                  {%endfor%}
                   {% endfor %}

                

    </tbody>
  </table>

templates/dashboard/dashboard_next_week.html
{% extends 'dashboard/base_dashboard.html' %}

{% load static %}



{% block content %}

<main>
  <h1>Dashboard</h1>
  {% comment %}
  <div class="data">
    <input type="date" />
  </div>
  {% endcomment %}


  <!-- END OF INSIGHTS -->

  <div class="middle">
    <div class="recent-orders">
    

      
      {% comment %}
      <div class="wrapper">
        <form method="get">
        <div class="search_box">
          <button class="search_btn"><i class="material-icons-sharp">person_search</i></button>
          <input type="text" id="tags" name="q" class="input_search" placeholder="Bemorlar">
          
        </form>
        </div>
      </div>
      {% endcomment %}

      <div class="wrapper">
        <div class="search_box">
          <form 
          hx-get="{% url 'dashboard_next_search' %}" 
          hx-target="#week" 
          hx-trigger="submit, input delay:0.3s">
    
          <input type="text" name="search" class="input_search" placeholder="Qidirish..." value="{{ search }}">
          </form>
         </div>
      </div>
      
  

      <div class="date button-group"> 
        <button class="button" type="button"><a href="{% url 'dashboard' %}">Kun</button></a> 
       <button class="button" type="button"> <a href="{% url 'dashboard_week' %}">Hafta</button></a> 
         </div>
         <div class="date button-group"> 
          <button class="button" type="button"><a href="{% url 'dashboard_week' %}"><i class="fa-solid fa-angles-left"></i></button></a> 
         <button class="button" type="button"> <a href="{% url 'dashboard_next_week' %}"><i class="fa-solid fa-angles-right"></i></button></a> 
           </div>
      
         <div id="week">
          {% include "dashboard/dashboard_next_search.html" %}
          </div>
         

      
    </div>
  </div>
</main>
<script type="text/javascript" src="{% static 'js/htmx.min.js' %}"></script>
<script>
  document.body.addEventListener('htmx:configRequest', (event) => {
    event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
  })
</script>

{% endblock content %}


</body>

</html>

templates/dashboard/dashboard_prev_search.html
<table>
    <thead>
      <tr>
            <th></th>
          {% for k,v in dictweek.items %}
            <th>{{v|date:"D, d/m"}}</th>
          {% endfor %}
      </tr>

    </thead>
    <tbody>
      {% for t in time %}
      <tr>
        <td>{{ t.time|date:"H:i" }}</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
      {% for k,v in dictweek.items %}
        {% for app in appointment %}
          {% if app.time|date:"H" == t.time|date:"H" %}
            {% if app.date == v %}
                <tr>
                  <th></th>
                  
                 
                  {% if k == 'dushanba' %} <td> <a href="{% url 'appointment_detail' app.pk  %}">{{ app.patient }}</a> </td> {% else %} <td></td> {% endif %}
                  {% if k == 'seshanba' %} <td> <a href="{% url 'appointment_detail' app.pk  %}">{{ app.patient }}</a> </td> {% else %} <td></td> {% endif %}
                  
                  {% if k == 'chorshanba' %} <td> <a href="{% url 'appointment_detail' app.pk  %}">{{ app.patient }}</a> </td> {% else %} <td></td> {% endif %}
                 
                  {% if k == 'payshanba' %} <td> <a href="{% url 'appointment_detail' app.pk  %}">{{ app.patient }}</a>  </td> {% else %} <td></td> {% endif %}
                 
                  {% if k == 'juma' %} <td> <a href="{% url 'appointment_detail' app.pk  %}">{{ app.patient }}</a>  </td> {% else %} <td></td> {% endif %}
                 
                  {% if k == 'shanba' %} <td> <a href="{% url 'appointment_detail' app.pk  %}">{{ app.patient }}</a> </td> {% else %} <td></td> {% endif %}
                 
                  {% if k == 'yakshanba' %} <td><a href="{% url 'appointment_detail' app.pk  %}">{{ app.patient }}</a>  </td> {% else %} <td></td> {% endif %}
                 
                  <td></td>
                  <td></td>
                  <td></td>
                  <td></td>
                  <td></td>
                  <td></td>


          {% endif %}
            {% endif %}
                {%endfor%}
                  {%endfor%}
                   {% endfor %}

                

    </tbody>
  </table>

templates/dashboard/dashboard_prev_week.html
{% extends 'dashboard/base_dashboard.html' %}

{% load static %}



{% block content %}

<main>
  <h1>Dashboard</h1>
  {% comment %}
  <div class="data">
    <input type="date" />
  </div>
  {% endcomment %}


  <!-- END OF INSIGHTS -->

  <div class="middle">
    <div class="recent-orders">
    

      
      {% comment %}
      <div class="wrapper">
        <form method="get">
        <div class="search_box">
          <button class="search_btn"><i class="material-icons-sharp">person_search</i></button>
          <input type="text" id="tags" name="q" class="input_search" placeholder="Bemorlar">
          
        </form>
        </div>
      </div>
      {% endcomment %}

      <div class="wrapper">
        <div class="search_box">
          <form 
          hx-get="{% url 'dashboard_prev_search' %}" 
          hx-target="#week" 
          hx-trigger="submit, input delay:0.3s">
    
          <input type="text" name="search" class="input_search" placeholder="Qidirish..." value="{{ search }}">
          </form>
         </div>
      </div>
      
  

      <div class="date button-group"> 
        <button class="button" type="button"><a href="{% url 'dashboard' %}">Kun</button></a> 
       <button class="button" type="button"> <a href="{% url 'dashboard_week' %}">Hafta</button></a> 
         </div>
         <div class="date button-group"> 
          <button class="button" type="button"><a href="{% url 'dashboard_prev_week' %}"><i class="fa-solid fa-angles-left"></i></button></a> 
         <button class="button" type="button"> <a href="{% url 'dashboard_week' %}"><i class="fa-solid fa-angles-right"></i></button></a> 
           </div>
      
         <div id="week">
          {% include "dashboard/dashboard_next_search.html" %}
          </div>
         

      
    </div>
  </div>
</main>
<script type="text/javascript" src="{% static 'js/htmx.min.js' %}"></script>
<script>
  document.body.addEventListener('htmx:configRequest', (event) => {
    event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
  })
</script>

{% endblock content %}


</body>

</html>

templates/dashboard/dashboard_search.html
<table>
        
    <thead>
      <tr>
        <th><i class="fa-solid fa-bars-staggered"></i></th>
        <th><i class="fa-solid fa-calendar-day"></i> Sana</th>
        <th><i class="fa-solid fa-clock"></i> Vaqt</th>
        <th><i class="fa-solid fa-teeth"></i> Bemor</th>
        <th><i class="fa-solid fa-stethoscope"></i> Diagnoz</th>
        
        <th><i class="fa-solid fa-spinner"></i> Status</th>
        <th><span class="material-icons-outlined">
          app_registration
          </span></th>
      </tr>
    </thead>
    <tbody>
      {% for t in time %}
      <tr>
        <td>{{ t.time|date:"H:i" }}</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
      
      {% for app in appointment %}
      {% if app.time|date:"H" == t.time|date:"H" %}
      {% if app.date == today %}         
      <tr >
        
        <th></th>
        <td><a href="{% url 'appointment_detail' app.pk  %}">{{ app.date |date:"D, d M, Y" }}</a></td>
        <td><a href="{% url 'appointment_detail' app.pk  %}">{{ app.time |date:"H:i" }}</a></td>
        <td >{{ app.patient }}</td>
        <td>{{ app.patient.diagnoz|truncatechars:150 }}</td>
        {% if app.status == "Kutilmoqda" %}
        <td>
          <span style="text-transform: uppercase; background-color: #fff2d6; color:#ffab00; 
          display: inline-block;
          padding: 0.52em 0.593em;
          font-size: 0.8125em;
          font-weight: 500;
          line-height: 1;
          text-align: center;
          white-space: nowrap;
          vertical-align: baseline;
          border-radius: 0.25rem;">{{ app.status }}
        </span>
      </td>
        {% elif app.status == "Yakunlandi" %}
        <td>
          <span style="text-transform: uppercase; background-color: #e8fadf; color:#71dd37; 
          display: inline-block;
          padding: 0.52em 0.593em;
          font-size: 0.8125em;
          font-weight: 500;
          line-height: 1;
          text-align: center;
          white-space: nowrap;
          vertical-align: baseline;
          border-radius: 0.25rem;">{{ app.status }}
        </span>  
        </td>
        {% elif app.status == "Bekor qilindi" %}
        <td>
          <span style="text-transform: uppercase; background-color: #ffc2c2; color:#ff3e1d; 
          display: inline-block;
          padding: 0.52em 0.593em;
          font-size: 0.8125em;
          font-weight: 500;
          line-height: 1;
          text-align: center;
          white-space: nowrap;
          vertical-align: baseline;
          border-radius: 0.25rem;">{{ app.status }}
        </span>  
        </td>
        {% endif %}
        <td>  <form method="post" action="{% url 'status_edit' app.pk %}">{% csrf_token %}<select id="status" style="background-color:transparent; width: 30px;" name="status">
          <option selected>-🔽-</option>
          <option value="Yakunlandi">-🟢- </option>
          <option value="Kutilmoqda">-🟡-</option>
          <option value="Bekor qilindi">-🔴-</option>
        

          
      </select> <button type="submit"  style="background-color: transparent;"><i class="fa-solid fa-pen-to-square"></i></button></form></td>
      <td>
        
      </td>
        {% endif %}

        {% endif %}
    
        {% comment %}
        <td>{{ app.doctor }}</td>
        {% endcomment %}
          
       
       
        {%endfor%}
        {% endfor %}
  
      </tr>
   
    </tbody>
  </table>

templates/dashboard/dashboard_week.html
{% extends 'dashboard/base_dashboard.html' %}

{% load static %}



{% block content %}

<main>
  <h1>Dashboard</h1>
  {% comment %}
  <div class="data">
    <input type="date" />
  </div>
  {% endcomment %}


  <!-- END OF INSIGHTS -->

  <div class="middle">
    <div class="recent-orders">
    

      
      {% comment %}
      <div class="wrapper">
        <form method="get">
        <div class="search_box">
          <button class="search_btn"><i class="material-icons-sharp">person_search</i></button>
          <input type="text" id="tags" name="q" class="input_search" placeholder="Bemorlar">
          
        </form>
        </div>
      </div>
      {% endcomment %}

      <div class="wrapper">
        <div class="search_box">
          <form 
          hx-get="{% url 'dashboard_week_search' %}" 
          hx-target="#week" 
          hx-trigger="submit, input delay:0.3s">
    
          <input type="text" name="search" class="input_search" placeholder="Qidirish..." value="{{ search }}">
          </form>
         </div>
      </div>
      
   <div class="date button-group"> 
        <button class="button" type="button"><a href="{% url 'dashboard' %}">Kun</button></a> 
       <button class="button" type="button"> <a href="{% url 'dashboard_week' %}">Hafta</button></a> 
         </div>

      <div class="date button-group"> 
        <button class="button" type="button"><a href="{% url 'dashboard_prev_week' %}"><i class="fa-solid fa-angles-left"></i></button></a> 
       <button class="button" type="button"> <a href="{% url 'dashboard_next_week' %}"><i class="fa-solid fa-angles-right"></i></button></a> 
         </div>

      
         <div id="week">
          {% include "dashboard/dashboard_week_search.html" %}
          </div>
         

      
    </div>
  </div>
</main>
<script type="text/javascript" src="{% static 'js/htmx.min.js' %}"></script>
<script>
  document.body.addEventListener('htmx:configRequest', (event) => {
    event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
  })
</script>

{% endblock content %}


</body>

</html>

templates/dashboard/dashboard_week_search.html
<table>
    <thead>
      <tr>
            <th></th>
          {% for k,v in dictweek.items %}
            <th>{{v|date:"D, d/m"}}</th>
          {% endfor %}
      </tr>

    </thead>
    <tbody>
      {% for t in time %}
      <tr>
        <td>{{ t.time|date:"H:i" }}</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
      {% for k,v in dictweek.items %}
        {% for app in appointment %}
          {% if app.time|date:"H" == t.time|date:"H" %}
            {% if app.date == v %}
                <tr>
                  <th></th>
                  
                 
                  {% if k == 'dushanba' %} <td> <a href="{% url 'appointment_detail' app.pk  %}">{{ app.patient }}</a> </td> {% else %} <td></td> {% endif %}
                  {% if k == 'seshanba' %} <td> <a href="{% url 'appointment_detail' app.pk  %}">{{ app.patient }}</a> </td> {% else %} <td></td> {% endif %}
                  
                  {% if k == 'chorshanba' %} <td> <a href="{% url 'appointment_detail' app.pk  %}">{{ app.patient }}</a> </td> {% else %} <td></td> {% endif %}
                 
                  {% if k == 'payshanba' %} <td> <a href="{% url 'appointment_detail' app.pk  %}">{{ app.patient }}</a>  </td> {% else %} <td></td> {% endif %}
                 
                  {% if k == 'juma' %} <td> <a href="{% url 'appointment_detail' app.pk  %}">{{ app.patient }}</a>  </td> {% else %} <td></td> {% endif %}
                 
                  {% if k == 'shanba' %} <td> <a href="{% url 'appointment_detail' app.pk  %}">{{ app.patient }}</a> </td> {% else %} <td></td> {% endif %}
                 
                  {% if k == 'yakshanba' %} <td><a href="{% url 'appointment_detail' app.pk  %}">{{ app.patient }}</a>  </td> {% else %} <td></td> {% endif %}
                 
                  <td></td>
                  <td></td>
                  <td></td>
                  <td></td>
                  <td></td>
                  <td></td>


          {% endif %}
            {% endif %}
                {%endfor%}
                  {%endfor%}
                   {% endfor %}

                

    </tbody>
  </table>

templates/dashboard/list.html
{% load static %}
<html lang="en">
<head>
    <title>
        List View
    </title>
    <meta charset="utf-8">
    
</head>
<body>
    <main  class="ui container">
        <h1 class="ui header center aligned">List View</h1>
        <form 
            class="centred ui form"
            hx-get="{% url 'search' %}" 
            hx-target="#search-results"
            
            hx-trigger="submit, input delay:0.3s"
        >
            <input type="text" name="search" placeholder="Search..." value="{{ search }}">
        </form>
        <div id="search-results">
            {% include 'search_results.html' %}
        </div>
        
    </main>
   
    <script type="text/javascript" src="{% static 'js/htmx.min.js' %}"></script>
    <script>
      document.body.addEventListener('htmx:configRequest', (event) => {
        event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
      })
    </script>
</body>
</html>

templates/dashboard/search_results.html
{% if appointment %}
    <div class="ui cards">
        {% for app in appointment %}
            <div class="ui card">
                <div class="image">
                    <img src="{{ post.image.url }}">
                </div>
                <div class="content">
                    <a class="header">{{ app.patient }}</a>
                </div>
            </div>
        {% endfor %}
    </div>
{% else %}
    <h3 class="ui header center aligned">No results!</h3>               
{% endif %}